### ISSUE TITLE
Problem running under Linux

### ISSUE THREAD

**Issue by AntonBiryukovUofC** [maciejczyzewski/fast_gpu_voronoi#1]
Hey Maciej,

Your code does not seem to work under Linux. Here's what i got from your example. Any clues to how I could fix it ?

pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'Quadro P4000' on 'NVIDIA CUDA' at 0x55f3a6f046a0>:

<kernel>:2:26: warning: unknown OpenCL extension 'cl_ext_device_fission' - ignoring
#pragma OPENCL EXTENSION cl_ext_device_fission : enable
                         ^
<kernel>:35:29: error: expected expression
        int A = (step * cos(float( ((6.28/12) * i) )));
                            ^
<kernel>:36:29: error: expected expression
        int B = (step * sin(float( ((6.28/12) * i) )));

**Comment by AntonBiryukovUofC** [comment]
seems like translating the code to C friendly `(float)` rather than `float()` helped...Should we fix it through a PR ?

Though I see some weird artifacts in the output
![__1_debug](https://user-images.githubusercontent.com/17001819/84559946-72718600-acfc-11ea-8d37-75618adaf27b.png)


or like this:
```from fast_gpu_voronoi import Instance
from fast_gpu_voronoi.jfa import JFA_star,JFA_plus
from fast_gpu_voronoi.debug import save
import numpy as np

npts = 1500
size_xy = 500
random_pts = np.random.randint(2, size_xy-2, size=(npts, 2))

I = Instance(alg=JFA_plus, x=size_xy, y=size_xy, pts=random_pts)
I.run()
print(I.M.shape)  # (50, 50, 1)
save(I.M, I.x, I.y, force=True)  # __1_debug.png
```


![__1_debug](https://user-images.githubusercontent.com/17001819/84559984-c7150100-acfc-11ea-8aac-af6a292498f9.png)

**Comment by AntonBiryukovUofC** [comment]
But now I got a different issue:

clEnqueueReadBuffer failed: OUT_OF_RESOURCES

when running a code similar to your baseline:
```
from fast_gpu_voronoi import Instance
from fast_gpu_voronoi.jfa import JFA_star
from fast_gpu_voronoi.debug import save
import numpy as np

npts = 1500
random_pts = np.random.randint(2, npts-1, size=(int(npts/10), 2))

I = Instance(alg=JFA_star, x=npts, y=npts, pts=random_pts)
I.run()
print(I.M.shape)  # (50, 50, 1)
save(I.M, I.x, I.y, force=True)  # __1_debug.png
```

Any thoughts ?

**Comment by maciejczyzewski** [comment]
Hey!

Thanks for interesting discoveries in the code /& during execution.
I will need to dig deep to understand your problem (~2 days).

On another branch there is a code with slight improvements:
https://github.com/maciejczyzewski/fast_gpu_voronoi/tree/staging
Try this version and tell me if it started working 😃

**Comment by AntonBiryukovUofC** [comment]
Tried staging branch, similar output:
![__8_debug](https://user-images.githubusercontent.com/17001819/84599365-b6fd3e80-ae2e-11ea-9ed6-96aedf60ca01.png)

**Comment by maciejczyzewski** [comment]
Hey Anton,

@KamilPiechowiak just released new version of *staging*. It works fine for your example:

https://colab.research.google.com/drive/1feoho8M_1a4tOpYFDPkqDVJeWHwdhJox?usp=sharing

I put working version on *Google Colab*.

![849c6e0a-f9e5-452c-89dc-b4c5b2eb70eb](https://user-images.githubusercontent.com/1976088/84711647-1d857800-af67-11ea-8557-638cbd0fd10c.png)

![image](https://user-images.githubusercontent.com/1976088/84711815-6fc69900-af67-11ea-9d04-175ccb0766a6.png)

EDIT: new version is tagged as 0.0.3 on *pypi* (https://pypi.org/project/fast-gpu-voronoi/#history)

**Comment by AntonBiryukovUofC** [comment]
Thanks, will get back to testing!
:D

**Comment by AntonBiryukovUofC** [comment]
Looks like it's working now. I am curious what the critical fix was :)
It also seems like the speed has improved substantially.

Do you guys know by chance what the limits are re: number of points and size of the image ?
Assuming the GPU RAM available is ~6-7GB

**Comment by KamilPiechowiak** [comment]
Nice to hear it works. As for the fix, we were sometimes requesting data from the outside of the array. It didn't cause any problems on our GPUs but here it did ;-) .
On GPU in algorithm with applied noise we use 28 bytes per output pixel. With such amount of RAM even 15000x15000 image should be fine.

**Comment by AntonBiryukovUofC** [comment]
That's what I thought re: outside array. I am still perplexed as to why it worked on some gpus and failed here :)

**Comment by AntonBiryukovUofC** [comment]
No clue what i have done wrong, but after install of 0.0.3 now I am hitting this issue:
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
https://github.com/conda-forge/pyopencl-feedstock/issues/32

False alarm: rebooting helped. Something has to do with gpu drivers not used properly after the PC is awakened from "Suspend".

We can probably close this issue!

**Comment by AntonBiryukovUofC** [comment]
Do you guys develop on Macs ? It looks like KHR is something macOS related
